version: '3.4'

services:
  homebrokerspa:
    image: ${DOCKER_REGISTRY-}homebrokerspa
    build:
      context: .
      dockerfile: HomeBrokerSPA/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:443;http://+:80
    ports:
      - "80"
      - "443"
